# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 
  config.vm.box = "gusztavvargadr/ubuntu-server-2004-lts"
  config.vm.hostname = "web-rmg"

  config.vm.provider "virtualbox" do | vb |
    vb.name ="web_server"
    vb.memory = 3072
    vb.cpus = 2
  end
  
  config.vm.network "private_network" , ip: "172.16.0.0/16"
  config.vm.network "public_network" , ip: "10.99.0.0/16"

end
